name = "183rd"
prefix = "oetav"
author = "183rd"
template = "cba"
mainprefix = "z"
folder_optionals = true

files = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "extras/addons",
    "extras/keys",
    "AUTHORS.txt",
    "183rd.paa",
    ]


exclude = ["*.psd", "*.png", "*.tga"]


modname = "{{name}}"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip 183_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

[header_exts]
version = "{{git \"id 8\"}}"
